name: santoni-3.18

on:
  workflow_dispatch:
    inputs:
      device:
          description: 'Device'
          default: 'santoni'
          required: true
      repo:
          description: 'Kernel source'
          default: 'https://github.com/malkist01/4x.git'
          required: true
      branch:
          description: 'Kernel source branch'
          default: '10'
          required: true
      token:
          description: 'Telegram bot token'
          default: '7596553794:AAGoeg4VypmUfBqfUML5VWt5mjivN5-3ah8'
          required: true
      chat_id:
          description: 'Telegram chat id'
          default: '-1002287610863'
          required: true


env:
  TZ: Asia/Jakarta
  DEVICE: ${{ github.event.inputs.device }}
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  token: ${{ github.event.inputs.token }}
  chat_id: ${{ github.event.inputs.chat_id }}

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Initializing environment
        run: |
          git config --global user.name "malkist01"
          git config --global user.email "aripujiyanto0812@gmail.com"
          git clone https://github.com/akhilnarang/scripts x
          cd x/setup && bash android_build_env.sh

      - name: Compiling
        run: |
          if [ "${DEVICE}" = "santoni" ]; then
            wget https://raw.githubusercontent.com/malkist01/builder/main/scripts/4X-3.18.sh
            bash 4X-3.18.sh
          else
            echo "Device not supported yet"
          fi
