name: ARM64

on:
  workflow_dispatch:
    inputs:
      device:
          description: 'Device'
          default: 'samsung'
          required: true
      repo:
          description: 'Kernel source'
          default: 'https://github.com/malkist01/android_kernel_msm8917.git'
          required: true
      branch:
          description: 'Kernel source branch'
          default: 'lineage-19.1'
          required: true
      toolchain:
          description: 'Toolchain'
          default: 'https://github.com/malkist01/malkist-toolchain'
          required: true
      tc_branch:
          description: 'Toolchain branch'
          default: 'master'
          required: true
      defconfig:
          description: 'Toolchain branch'
          default: 'teletubies_defconfig'
          required: true
      token:
          description: 'Telegram bot token'
          default: '7596553794:AAGoeg4VypmUfBqfUML5VWt5mjivN5-3ah8'
          required: false
      chat_id:
          description: 'Telegram chat id'
          default: '-1002287610863'
          required: false


env:
  TZ: Asia/Jakarta
  DEVICE: ${{ github.event.inputs.device }}
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  token: ${{ github.event.inputs.token }}
  chat_id: ${{ github.event.inputs.chat_id }}

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Initializing environment
        run: |
          git config --global user.name "malkist01"
          git config --global user.email "aripujiyanto0812@gmail.com"
          git clone https://github.com/akhilnarang/scripts x
          cd x/setup && bash android_build_env.sh

      - name: Compiling
        run: |
          if [ "${DEVICE}" = "samsung" ]; then
            wget https://raw.githubusercontent.com/malkist01/builder/main/scripts/arm64.sh
            bash arm64.sh
          else
            echo "Device not supported yet"
          fi
