name: j4primelte

on:
  workflow_dispatch:
    inputs:
      device:
          description: 'Device'
          default: 'samsung'
          required: true
      repo:
          description: 'Kernel source link (dont include . git at the end)'
          default: 'https://github.com/malkist01/Jenem.git'
          required: true
      branch:
          description: 'Kernel source branch'
          default: 'ksu'
          required: true
      token:
          description: 'Telegram bot token'
          default: '7596553794:AAGoeg4VypmUfBqfUML5VWt5mjivN5-3ah8'
          required: true
      chat_id:
          description: 'Telegram chat id'
          default: '-1002287610863'
          required: true

env:
  TZ: Asia/Jakarta
  DEVICE: ${{ github.event.inputs.device }}
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  token: ${{ github.event.inputs.token }}
  chat_id: ${{ github.event.inputs.chat_id }}

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Initializing environment
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git make bc bison \
          openssl curl zip kmod cpio flex libelf-dev \
          libssl-dev libtfm-dev wget device-tree-compiler \
          ca-certificates python3 python2 binutils \
          binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi

      - name: Compiling
        run: |
          if [ "${DEVICE}" = "samsung" ]; then
            wget https://raw.githubusercontent.com/malkist01/builder/main/scripts/j4primelte.sh
            bash j4primelte.sh
          else
            echo "Device not supported yet"
          fi
