name: Test

on:
  workflow_dispatch:
    inputs:
      device:
          description: 'Device'
          default: 'mido'
          required: true
      repo:
          description: 'Kernel source'
          default: 'https://github.com/malkist01/mid.git'
          required: true
      branch:
          description: 'Kernel source branch'
          default: '14'
          required: true
      token:
          description: 'Telegram bot token'
          default: '7596553794:AAGoeg4VypmUfBqfUML5VWt5mjivN5-3ah8'
          required: true
      chat_id:
          description: 'Telegram chat id'
          default: '-1002287610863'
          required: true


env:
  TZ: Asia/Jakarta
  DEVICE: ${{ github.event.inputs.device }}
  REPO: ${{ github.event.inputs.repo }}
  BRANCH: ${{ github.event.inputs.branch }}
  token: ${{ github.event.inputs.token }}
  chat_id: ${{ github.event.inputs.chat_id }}

jobs:
  kernel-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Initializing environment
        run: |
          git config --global user.name "malkist01"
          git config --global user.email "aripujiyanto0812@gmail.com"
          git clone https://github.com/akhilnarang/scripts x
          cd x/setup && bash android_build_env.sh 

      - name: Compiling
        run: |
          if [ "${DEVICE}" = "mido" ]; then
            wget https://raw.githubusercontent.com/malkist01/builder/main/scripts/test.sh
            bash test.sh
          else
            echo "Device not supported yet"
          fi

      - name: Processing Submodules
        run: |
          git submodule update --init --remote --rebase --recursive android/Installer
          git submodule update --init --remote --rebase --recursive KernelSU
          sed -i -e '$a\'$'\n''CONFIG_KSU=y\nCONFIG_KSU_SUSFS=y\nCONFIG_KSU_MANUAL_HOOK=y\nCONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y\nCONFIG_KSU_SUSFS_SUS_PATH=y\nCONFIG_KSU_SUSFS_SUS_MOUNT=y\nCONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y\nCONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y\nCONFIG_KSU_SUSFS_SUS_KSTAT=y\nCONFIG_KSU_SUSFS_TRY_UMOUNT=y\nCONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y\nCONFIG_KSU_SUSFS_SPOOF_UNAME=y\nCONFIG_KSU_SUSFS_ENABLE_LOG=y\nCONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y\nCONFIG_KSU_SUSFS_OPEN_REDIRECT=y' arch/arm64/configs/teletubies_defconfig
          git submodule update --init --remote --rebase --recursive utils         